# Generated by Django 3.0.2 on 2020-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.TextField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
